/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chazzbg.easyfilesharing;

import java.io.File;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author chazz
 */
public class MainView extends JFrame  {
	ClientAlive clientAlive = null;
	CheckAlive checkAlive = null;
	FileReceive fileReceive = null;
	private File selectedFile = null;
	private File recivePath = null;
	
	/**
	 * Creates new form MainView
	 */
	public MainView() {
		
		initComponents();
		clientAlive = new ClientAlive(this);
		clientAlive.start();
		checkAlive = new CheckAlive(this);
		checkAlive.start();
		fileReceive  = new FileReceive(this);
		fileReceive.start();
		if(recivePath == null){
			recivePath = new File(System.getProperty("user.home"));
			pathField.setText(recivePath.getPath());
			
		}
		
	}

	
	
	
	public void writeDebug(String msg){
		//debug.append(msg+"\n");
		System.out.println(msg);
	}
	
	public void toggleCheckButton( boolean state){
		checkButton.setEnabled(state);

	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        sendButton = new javax.swing.JButton();
        sendField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sendFileBrowseButton = new javax.swing.JButton();
        pathField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pathForReceiveButton = new javax.swing.JButton();
        hostsListComboBox = new javax.swing.JComboBox();
        checkButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        localaddrLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy File Sharing");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(getClass().getResource("/com/chazzbg/easyfilesharing/res/icon.png")).getImage());
        setLocationByPlatform(true);
        setName("mainFrame"); // NOI18N
        setResizable(false);

        jProgressBar1.setPreferredSize(new java.awt.Dimension(150, 25));
        jProgressBar1.setString("");

        sendButton.setText("Send file");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        sendField.setEditable(false);

        jLabel1.setText("File for send");

        sendFileBrowseButton.setText("Browse");
        sendFileBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileBrowseButtonActionPerformed(evt);
            }
        });

        pathField.setEditable(false);

        jLabel2.setText("Path for Receive");

        pathForReceiveButton.setText("Browse");
        pathForReceiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathForReceiveButtonActionPerformed(evt);
            }
        });

        hostsListComboBox.setEnabled(false);

        checkButton.setText("Refresh");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Local Addres:");

        jLabel4.setText("Active clients");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hostsListComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sendField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendFileBrowseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localaddrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pathForReceiveButton))
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostsListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton)
                    .addComponent(sendFileBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathForReceiveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(localaddrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
       checkAlive = new CheckAlive(this);
	   checkAlive.start();
    }//GEN-LAST:event_checkButtonActionPerformed

    private void pathForReceiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathForReceiveButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(recivePath);
		fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
       
		fc.showDialog(rootPane, "Select");
		
        recivePath = fc.getSelectedFile();
		
        pathField.setText(recivePath.getAbsolutePath());
    }//GEN-LAST:event_pathForReceiveButtonActionPerformed

    private void sendFileBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFileBrowseButtonActionPerformed

        final JFileChooser fc = new JFileChooser();
		
		if(selectedFile != null) {
			fc.setCurrentDirectory(new File(selectedFile.getAbsolutePath()));
		}
		
		fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.showDialog(rootPane, "Select");
		

        selectedFile = fc.getSelectedFile();
        sendField.setText(selectedFile.getAbsolutePath());

    }//GEN-LAST:event_sendFileBrowseButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed

        if(hostsListComboBox.getSelectedItem() == null){
            showError("You have to select active host!");
        } else {
            String host =  hostsListComboBox.getSelectedItem().toString();
			File f = getSelectedFile();
			if(f==null) {
				showError("Select file for sending!");
			} else {
				new FileSend(this, host,getSelectedFile()).start();
			}
        }

    }//GEN-LAST:event_sendButtonActionPerformed
	public void toggleSendButton(boolean state){
		sendButton.setEnabled(state);
	}
	public void toggleProgressBar(boolean state){
		
		jProgressBar1.setIndeterminate(state);
		
	}
	public void updateHostList(ArrayList<String> hosts){
		
		String[] hostList = new String[hosts.size()];
		
		int i = 0;
		for(String host : hosts){
			hostList[i] = host;
			System.out.println(host);
			i++;
		}
		hostsListComboBox.setModel(new DefaultComboBoxModel(hosts.toArray()));
		if(hostList.length >0){
			hostsListComboBox.setEnabled(true);
		
		} else {
			hostsListComboBox.setEnabled(false);
		}
	}
	
	
	
	public void showMessage(String msg) {
		JOptionPane.showMessageDialog(rootPane, msg, "Message", JOptionPane.INFORMATION_MESSAGE);
	}
	public void showError(String err) {
		JOptionPane.showMessageDialog(rootPane, err, "Error" , JOptionPane.ERROR_MESSAGE);
	}
	public int showChoose(String msg, String title){
		Object[] options = {"No","Yes"};
		
	
		int opt =  JOptionPane.showOptionDialog(rootPane, msg, title,
				JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null,
				options,options[1]);
		
		return opt;
		
	}

	public File getSelectedFile() {
		return selectedFile;
	}
	public File getRecivePath() {
		return recivePath;
	}
	public void setProgressBarValue(int val){
		
		jProgressBar1.setValue(val);
	}
	
	public void setLocalAddLabel(String host){
		localaddrLabel.setText(host);
	}
	public void setSpeed(float speed) {	
		if(speed >0){
			BigDecimal bd  = new BigDecimal(speed);
			bd = bd.setScale(2, BigDecimal.ROUND_HALF_UP);
			speed = (float) bd.doubleValue();
			
			jProgressBar1.setStringPainted(true);
			jProgressBar1.setString(speed + "MB/s");
			
		} else {
			
			jProgressBar1.setStringPainted(false);
		}
	}
	/**
	 * @param args the command line arguments
	 */
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkButton;
    private javax.swing.JComboBox hostsListComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel localaddrLabel;
    private javax.swing.JTextField pathField;
    private javax.swing.JButton pathForReceiveButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField sendField;
    private javax.swing.JButton sendFileBrowseButton;
    // End of variables declaration//GEN-END:variables

	

	
}
